// <auto-generated />
using System;
using CleanCllinicSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanCllinicSystem.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20241211093145_updatespeci")]
    partial class updatespeci
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanCllinicSystem.models.Clinic", b =>
                {
                    b.Property<string>("spe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("num_of_slots")
                        .HasColumnType("int");

                    b.HasKey("spe");

                    b.ToTable("clinics");
                });

            modelBuilder.Entity("CleanCllinicSystem.models.Patient", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pid"));

                    b.Property<int>("RGender")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("pname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pid");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("CleanCllinicSystem.models.booking", b =>
                {
                    b.Property<int>("pid")
                        .HasColumnType("int");

                    b.Property<string>("spec")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("bookid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookid"));

                    b.Property<int>("slot_number")
                        .HasColumnType("int");

                    b.HasKey("pid", "spec", "date");

                    b.HasIndex("spec");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("CleanCllinicSystem.models.booking", b =>
                {
                    b.HasOne("CleanCllinicSystem.models.Patient", "patients")
                        .WithMany("bookings")
                        .HasForeignKey("pid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanCllinicSystem.models.Clinic", "clinics")
                        .WithMany("bookings")
                        .HasForeignKey("spec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinics");

                    b.Navigation("patients");
                });

            modelBuilder.Entity("CleanCllinicSystem.models.Clinic", b =>
                {
                    b.Navigation("bookings");
                });

            modelBuilder.Entity("CleanCllinicSystem.models.Patient", b =>
                {
                    b.Navigation("bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
